//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("multiinterpretadorModel", "FK_PerfilId", "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebUI.perfil), "rolperfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebUI.rolperfil), true)]
[assembly: EdmRelationshipAttribute("multiinterpretadorModel", "FK_Rol_X_Id", "rol", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebUI.rol), "rolperfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebUI.rolperfil), true)]
[assembly: EdmRelationshipAttribute("multiinterpretadorModel", "fk_estadoUsuario", "estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebUI.estado), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebUI.usuario), true)]
[assembly: EdmRelationshipAttribute("multiinterpretadorModel", "fk_perfilUsuario", "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebUI.perfil), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebUI.usuario), true)]
[assembly: EdmRelationshipAttribute("multiinterpretadorModel", "fk_bitacora", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebUI.usuario), "bitacora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebUI.bitacora), true)]

#endregion

namespace WebUI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class multiinterpretadorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new multiinterpretadorEntities object using the connection string found in the 'multiinterpretadorEntities' section of the application configuration file.
        /// </summary>
        public multiinterpretadorEntities() : base("name=multiinterpretadorEntities", "multiinterpretadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new multiinterpretadorEntities object.
        /// </summary>
        public multiinterpretadorEntities(string connectionString) : base(connectionString, "multiinterpretadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new multiinterpretadorEntities object.
        /// </summary>
        public multiinterpretadorEntities(EntityConnection connection) : base(connection, "multiinterpretadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<estado> estado
        {
            get
            {
                if ((_estado == null))
                {
                    _estado = base.CreateObjectSet<estado>("estado");
                }
                return _estado;
            }
        }
        private ObjectSet<estado> _estado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<perfil> perfil
        {
            get
            {
                if ((_perfil == null))
                {
                    _perfil = base.CreateObjectSet<perfil>("perfil");
                }
                return _perfil;
            }
        }
        private ObjectSet<perfil> _perfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rol> rol
        {
            get
            {
                if ((_rol == null))
                {
                    _rol = base.CreateObjectSet<rol>("rol");
                }
                return _rol;
            }
        }
        private ObjectSet<rol> _rol;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rolperfil> rolperfil
        {
            get
            {
                if ((_rolperfil == null))
                {
                    _rolperfil = base.CreateObjectSet<rolperfil>("rolperfil");
                }
                return _rolperfil;
            }
        }
        private ObjectSet<rolperfil> _rolperfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bitacora> bitacora
        {
            get
            {
                if ((_bitacora == null))
                {
                    _bitacora = base.CreateObjectSet<bitacora>("bitacora");
                }
                return _bitacora;
            }
        }
        private ObjectSet<bitacora> _bitacora;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the estado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToestado(estado estado)
        {
            base.AddObject("estado", estado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the perfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperfil(perfil perfil)
        {
            base.AddObject("perfil", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rol EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorol(rol rol)
        {
            base.AddObject("rol", rol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rolperfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorolperfil(rolperfil rolperfil)
        {
            base.AddObject("rolperfil", rolperfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bitacora EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobitacora(bitacora bitacora)
        {
            base.AddObject("bitacora", bitacora);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="bitacora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bitacora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bitacora object.
        /// </summary>
        /// <param name="bitacoraId">Initial value of the BitacoraId property.</param>
        /// <param name="bitacora_UsuarioId">Initial value of the Bitacora_UsuarioId property.</param>
        /// <param name="bitacoraLenguaje">Initial value of the BitacoraLenguaje property.</param>
        /// <param name="bitacoraDescripcionEvento">Initial value of the BitacoraDescripcionEvento property.</param>
        public static bitacora Createbitacora(global::System.Int32 bitacoraId, global::System.Int32 bitacora_UsuarioId, global::System.String bitacoraLenguaje, global::System.String bitacoraDescripcionEvento)
        {
            bitacora bitacora = new bitacora();
            bitacora.BitacoraId = bitacoraId;
            bitacora.Bitacora_UsuarioId = bitacora_UsuarioId;
            bitacora.BitacoraLenguaje = bitacoraLenguaje;
            bitacora.BitacoraDescripcionEvento = bitacoraDescripcionEvento;
            return bitacora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BitacoraId
        {
            get
            {
                return _BitacoraId;
            }
            set
            {
                if (_BitacoraId != value)
                {
                    OnBitacoraIdChanging(value);
                    ReportPropertyChanging("BitacoraId");
                    _BitacoraId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BitacoraId");
                    OnBitacoraIdChanged();
                }
            }
        }
        private global::System.Int32 _BitacoraId;
        partial void OnBitacoraIdChanging(global::System.Int32 value);
        partial void OnBitacoraIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bitacora_UsuarioId
        {
            get
            {
                return _Bitacora_UsuarioId;
            }
            set
            {
                OnBitacora_UsuarioIdChanging(value);
                ReportPropertyChanging("Bitacora_UsuarioId");
                _Bitacora_UsuarioId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bitacora_UsuarioId");
                OnBitacora_UsuarioIdChanged();
            }
        }
        private global::System.Int32 _Bitacora_UsuarioId;
        partial void OnBitacora_UsuarioIdChanging(global::System.Int32 value);
        partial void OnBitacora_UsuarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BitacoraLenguaje
        {
            get
            {
                return _BitacoraLenguaje;
            }
            set
            {
                OnBitacoraLenguajeChanging(value);
                ReportPropertyChanging("BitacoraLenguaje");
                _BitacoraLenguaje = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BitacoraLenguaje");
                OnBitacoraLenguajeChanged();
            }
        }
        private global::System.String _BitacoraLenguaje;
        partial void OnBitacoraLenguajeChanging(global::System.String value);
        partial void OnBitacoraLenguajeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BitacoraDescripcionEvento
        {
            get
            {
                return _BitacoraDescripcionEvento;
            }
            set
            {
                OnBitacoraDescripcionEventoChanging(value);
                ReportPropertyChanging("BitacoraDescripcionEvento");
                _BitacoraDescripcionEvento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BitacoraDescripcionEvento");
                OnBitacoraDescripcionEventoChanged();
            }
        }
        private global::System.String _BitacoraDescripcionEvento;
        partial void OnBitacoraDescripcionEventoChanging(global::System.String value);
        partial void OnBitacoraDescripcionEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BitacoraSentencia
        {
            get
            {
                return _BitacoraSentencia;
            }
            set
            {
                OnBitacoraSentenciaChanging(value);
                ReportPropertyChanging("BitacoraSentencia");
                _BitacoraSentencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BitacoraSentencia");
                OnBitacoraSentenciaChanged();
            }
        }
        private global::System.String _BitacoraSentencia;
        partial void OnBitacoraSentenciaChanging(global::System.String value);
        partial void OnBitacoraSentenciaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_bitacora", "usuario")]
        public usuario usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("multiinterpretadorModel.fk_bitacora", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("multiinterpretadorModel.fk_bitacora", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("multiinterpretadorModel.fk_bitacora", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("multiinterpretadorModel.fk_bitacora", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class estado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new estado object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static estado Createestado(global::System.Int32 id, global::System.String descripcion)
        {
            estado estado = new estado();
            estado.Id = id;
            estado.Descripcion = descripcion;
            return estado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_estadoUsuario", "usuario")]
        public EntityCollection<usuario> usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("multiinterpretadorModel.fk_estadoUsuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("multiinterpretadorModel.fk_estadoUsuario", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new perfil object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static perfil Createperfil(global::System.Int32 id, global::System.String nombre)
        {
            perfil perfil = new perfil();
            perfil.Id = id;
            perfil.Nombre = nombre;
            return perfil;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "FK_PerfilId", "rolperfil")]
        public EntityCollection<rolperfil> rolperfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<rolperfil>("multiinterpretadorModel.FK_PerfilId", "rolperfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<rolperfil>("multiinterpretadorModel.FK_PerfilId", "rolperfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_perfilUsuario", "usuario")]
        public EntityCollection<usuario> usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("multiinterpretadorModel.fk_perfilUsuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("multiinterpretadorModel.fk_perfilUsuario", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="rol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rol object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static rol Createrol(global::System.Int32 id, global::System.String nombre)
        {
            rol rol = new rol();
            rol.Id = id;
            rol.Nombre = nombre;
            return rol;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "FK_Rol_X_Id", "rolperfil")]
        public EntityCollection<rolperfil> rolperfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<rolperfil>("multiinterpretadorModel.FK_Rol_X_Id", "rolperfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<rolperfil>("multiinterpretadorModel.FK_Rol_X_Id", "rolperfil", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="rolperfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rolperfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rolperfil object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="perfilId">Initial value of the PerfilId property.</param>
        /// <param name="rolId">Initial value of the RolId property.</param>
        public static rolperfil Createrolperfil(global::System.Int32 id, global::System.Int32 perfilId, global::System.Int32 rolId)
        {
            rolperfil rolperfil = new rolperfil();
            rolperfil.Id = id;
            rolperfil.PerfilId = perfilId;
            rolperfil.RolId = rolId;
            return rolperfil;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PerfilId
        {
            get
            {
                return _PerfilId;
            }
            set
            {
                OnPerfilIdChanging(value);
                ReportPropertyChanging("PerfilId");
                _PerfilId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PerfilId");
                OnPerfilIdChanged();
            }
        }
        private global::System.Int32 _PerfilId;
        partial void OnPerfilIdChanging(global::System.Int32 value);
        partial void OnPerfilIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RolId
        {
            get
            {
                return _RolId;
            }
            set
            {
                OnRolIdChanging(value);
                ReportPropertyChanging("RolId");
                _RolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RolId");
                OnRolIdChanged();
            }
        }
        private global::System.Int32 _RolId;
        partial void OnRolIdChanging(global::System.Int32 value);
        partial void OnRolIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "FK_PerfilId", "perfil")]
        public perfil perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.FK_PerfilId", "perfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.FK_PerfilId", "perfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<perfil> perfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.FK_PerfilId", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<perfil>("multiinterpretadorModel.FK_PerfilId", "perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "FK_Rol_X_Id", "rol")]
        public rol rol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("multiinterpretadorModel.FK_Rol_X_Id", "rol").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("multiinterpretadorModel.FK_Rol_X_Id", "rol").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<rol> rolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("multiinterpretadorModel.FK_Rol_X_Id", "rol");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<rol>("multiinterpretadorModel.FK_Rol_X_Id", "rol", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="multiinterpretadorModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="usuarioId">Initial value of the UsuarioId property.</param>
        /// <param name="usuarioNick">Initial value of the UsuarioNick property.</param>
        /// <param name="usuarioClave">Initial value of the UsuarioClave property.</param>
        /// <param name="usuarioEstado">Initial value of the UsuarioEstado property.</param>
        /// <param name="usuarioPerfilId">Initial value of the UsuarioPerfilId property.</param>
        /// <param name="usuarioNombre">Initial value of the UsuarioNombre property.</param>
        public static usuario Createusuario(global::System.Int32 usuarioId, global::System.String usuarioNick, global::System.String usuarioClave, global::System.Int32 usuarioEstado, global::System.Int32 usuarioPerfilId, global::System.String usuarioNombre)
        {
            usuario usuario = new usuario();
            usuario.UsuarioId = usuarioId;
            usuario.UsuarioNick = usuarioNick;
            usuario.UsuarioClave = usuarioClave;
            usuario.UsuarioEstado = usuarioEstado;
            usuario.UsuarioPerfilId = usuarioPerfilId;
            usuario.UsuarioNombre = usuarioNombre;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioId
        {
            get
            {
                return _UsuarioId;
            }
            set
            {
                if (_UsuarioId != value)
                {
                    OnUsuarioIdChanging(value);
                    ReportPropertyChanging("UsuarioId");
                    _UsuarioId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UsuarioId");
                    OnUsuarioIdChanged();
                }
            }
        }
        private global::System.Int32 _UsuarioId;
        partial void OnUsuarioIdChanging(global::System.Int32 value);
        partial void OnUsuarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioNick
        {
            get
            {
                return _UsuarioNick;
            }
            set
            {
                OnUsuarioNickChanging(value);
                ReportPropertyChanging("UsuarioNick");
                _UsuarioNick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioNick");
                OnUsuarioNickChanged();
            }
        }
        private global::System.String _UsuarioNick;
        partial void OnUsuarioNickChanging(global::System.String value);
        partial void OnUsuarioNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioClave
        {
            get
            {
                return _UsuarioClave;
            }
            set
            {
                OnUsuarioClaveChanging(value);
                ReportPropertyChanging("UsuarioClave");
                _UsuarioClave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioClave");
                OnUsuarioClaveChanged();
            }
        }
        private global::System.String _UsuarioClave;
        partial void OnUsuarioClaveChanging(global::System.String value);
        partial void OnUsuarioClaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioEstado
        {
            get
            {
                return _UsuarioEstado;
            }
            set
            {
                OnUsuarioEstadoChanging(value);
                ReportPropertyChanging("UsuarioEstado");
                _UsuarioEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioEstado");
                OnUsuarioEstadoChanged();
            }
        }
        private global::System.Int32 _UsuarioEstado;
        partial void OnUsuarioEstadoChanging(global::System.Int32 value);
        partial void OnUsuarioEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioPerfilId
        {
            get
            {
                return _UsuarioPerfilId;
            }
            set
            {
                OnUsuarioPerfilIdChanging(value);
                ReportPropertyChanging("UsuarioPerfilId");
                _UsuarioPerfilId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioPerfilId");
                OnUsuarioPerfilIdChanged();
            }
        }
        private global::System.Int32 _UsuarioPerfilId;
        partial void OnUsuarioPerfilIdChanging(global::System.Int32 value);
        partial void OnUsuarioPerfilIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioNombre
        {
            get
            {
                return _UsuarioNombre;
            }
            set
            {
                OnUsuarioNombreChanging(value);
                ReportPropertyChanging("UsuarioNombre");
                _UsuarioNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioNombre");
                OnUsuarioNombreChanged();
            }
        }
        private global::System.String _UsuarioNombre;
        partial void OnUsuarioNombreChanging(global::System.String value);
        partial void OnUsuarioNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] UsuarioFoto
        {
            get
            {
                return StructuralObject.GetValidValue(_UsuarioFoto);
            }
            set
            {
                OnUsuarioFotoChanging(value);
                ReportPropertyChanging("UsuarioFoto");
                _UsuarioFoto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsuarioFoto");
                OnUsuarioFotoChanged();
            }
        }
        private global::System.Byte[] _UsuarioFoto;
        partial void OnUsuarioFotoChanging(global::System.Byte[] value);
        partial void OnUsuarioFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsuarioEmail
        {
            get
            {
                return _UsuarioEmail;
            }
            set
            {
                OnUsuarioEmailChanging(value);
                ReportPropertyChanging("UsuarioEmail");
                _UsuarioEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsuarioEmail");
                OnUsuarioEmailChanged();
            }
        }
        private global::System.String _UsuarioEmail;
        partial void OnUsuarioEmailChanging(global::System.String value);
        partial void OnUsuarioEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UsuarioIsReset
        {
            get
            {
                return _UsuarioIsReset;
            }
            set
            {
                OnUsuarioIsResetChanging(value);
                ReportPropertyChanging("UsuarioIsReset");
                _UsuarioIsReset = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioIsReset");
                OnUsuarioIsResetChanged();
            }
        }
        private Nullable<global::System.Int32> _UsuarioIsReset;
        partial void OnUsuarioIsResetChanging(Nullable<global::System.Int32> value);
        partial void OnUsuarioIsResetChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_estadoUsuario", "estado")]
        public estado estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estado>("multiinterpretadorModel.fk_estadoUsuario", "estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estado>("multiinterpretadorModel.fk_estadoUsuario", "estado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<estado> estadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<estado>("multiinterpretadorModel.fk_estadoUsuario", "estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<estado>("multiinterpretadorModel.fk_estadoUsuario", "estado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_perfilUsuario", "perfil")]
        public perfil perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.fk_perfilUsuario", "perfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.fk_perfilUsuario", "perfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<perfil> perfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("multiinterpretadorModel.fk_perfilUsuario", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<perfil>("multiinterpretadorModel.fk_perfilUsuario", "perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("multiinterpretadorModel", "fk_bitacora", "bitacora")]
        public EntityCollection<bitacora> bitacora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<bitacora>("multiinterpretadorModel.fk_bitacora", "bitacora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<bitacora>("multiinterpretadorModel.fk_bitacora", "bitacora", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
